title: Rubik Gita
description: Solving the Bhagavad Gita like a Rubik Cube. That's right folks! Step right up and solve the mysteries once and for all! Too many confusing twists and turns in the narrative of the Bhagavad Gita? Is Wisdom better than Action, as Arjuna asks Krishna? Or is devotion the final common denominator? Why does Krishna refer to himself in the Third Person in some versses, and in the First Person in others? Who really wrote the Bhagavad Gita and why? Why is it impossible to overcome the Brahmins? So many questions!! Of the thousands who endeavor, hardly one finds the Truth. Subscribe now!
author: Saurabh Sikka
email: saurabhsikka@icloud.com
lang: en-us
copyright: "&#x2117; &amp; &#xA9; 2021"
logo: /assets/img/logo.png
baseurl: "/rubik-gita" # the subpath of your site, e.g. /blog
url: "https://nacicatus.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
